language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_tests

services:
  - postgresql

addons:
  postgresql: 13
  apt:
    packages:
      - postgresql-13

before_script:
  - psql -c 'create database  registration_tests;' -U postgres
  - psql -U postgres -d registration_tests -a -f reg-numbersDB.sql
